{"uid":"4a39716b6f0cff75","name":"An uncaught error was detected outside of a test","fullName":"cypress\\API\\API-spec.cy.js#An uncaught error was detected outside of a test","historyId":"d54fb2abfeae07632b82610489f0a975:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1717397642223,"stop":1717397642340,"duration":117},"status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > process is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"ReferenceError: The following error originated from your test code, not from Cypress.\n\n  > process is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at ./node_modules/ci-info/index.js (webpack://interactive-ventures/./node_modules/ci-info/index.js:5:0)\n    at __webpack_require__ (webpack://interactive-ventures/webpack/bootstrap:19:0)\n    at ./node_modules/is-ci/index.js (webpack://interactive-ventures/./node_modules/is-ci/index.js:3:0)\n    at __webpack_require__ (webpack://interactive-ventures/webpack/bootstrap:19:0)\n    at ./node_modules/cypress/lib/util.js (webpack://interactive-ventures/./node_modules/cypress/lib/util.js:12:13)\n    at __webpack_require__ (webpack://interactive-ventures/webpack/bootstrap:19:0)\n    at ./node_modules/cypress/index.js (webpack://interactive-ventures/./node_modules/cypress/index.js:6:13)\n    at __webpack_require__ (webpack://interactive-ventures/webpack/bootstrap:19:0)\n    at eval (webpack://interactive-ventures/./cypress/API/API-spec.cy.js:3:16)\n    at eval (https://hr-challenge.dev.tapyou.com/__cypress/tests?p=cypress\\API\\API-spec.cy.js:152993:3)\nFrom previous event:\n    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (https://hr-challenge.dev.tapyou.com/__cypress/runner/cypress_runner.js:3486:19)\n    at Promise._then (https://hr-challenge.dev.tapyou.com/__cypress/runner/cypress_runner.js:1239:17)\n    at Promise.then (https://hr-challenge.dev.tapyou.com/__cypress/runner/cypress_runner.js:1132:17)\n    at runScriptsFromUrls (https://hr-challenge.dev.tapyou.com/__cypress/runner/cypress_runner.js:111321:136)\n    at Object.runScripts (https://hr-challenge.dev.tapyou.com/__cypress/runner/cypress_runner.js:111362:12)\n    at $Cypress.onSpecWindow (https://hr-challenge.dev.tapyou.com/__cypress/runner/cypress_runner.js:40889:67)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"aa3807b6e2920ce9","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Ð¡ypress is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1717349447806,"stop":1717349447851,"duration":45}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"4a39716b6f0cff75.json","parameterValues":[]}